### ISSUE TITLE
how to export onnx 

### ISSUE THREAD

**Issue by xll426** [pranavphoenix/WaveMixSR#5]

**Comment by xll426** [comment]
Traceback (most recent call last):
  File "test.py", line 399, in <module>
    torch.onnx.export(model, images, exported_model_path,verbose=True, opset_version=15)
  File "/home/work/anaconda3/envs/hat/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/home/work/anaconda3/envs/hat/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/home/work/anaconda3/envs/hat/lib/python3.8/site-packages/torch/onnx/utils.py", line 1110, in _export
    ) = graph._export_onnx(  # type: ignore[attr-defined]
RuntimeError: ONNX export failed: Couldn't export Python operator AFB2D
